name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP Deploy
      id: ftp_deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /htdocs/
        exclude: |
          private/config.php

    - name: Discord notification - Success
      uses: cl8dep/action-discord@v0
      if: success()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: 'FTP deploy completed successfully! All files are now updated.'
    - name: Discord notification - Failure
      uses: cl8dep/action-discord@v0
      if: failure() 
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: 'FTP deploy failed. Please check the logs for errors.'
